# Generated by Django 4.0 on 2022-01-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        ('cities', '0003_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')),
                ('route_travel_time', models.PositiveSmallIntegerField(verbose_name='Время маршрута')),
                ('route_from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_city_set', to='cities.city', verbose_name='Начальный пункт')),
                ('route_to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_city_set', to='cities.city', verbose_name='Конечный путь')),
                ('route_trains', models.ManyToManyField(to='trains.Train', verbose_name='Список поездов')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['route_name'],
            },
        ),
    ]
